# Generated by Django 5.2.8 on 2025-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_found', models.DateField(auto_now_add=True)),
                ('contact_info', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('keywords', models.CharField(help_text='Comma-separated keywords for search', max_length=200)),
            ],
        ),
    ]
