# Generated by Django 5.2.8 on 2025-11-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='image',
        ),
    ]
